name: 'Build sched-ext/scx'
inputs:
  output-dir:
    description: 'Path to the output of scx build'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build sched-ext/scx in container
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
      run: ${{ github.action_path }}/action.sh
