name: 'Tar build artifacts'
inputs:
  arch:
    description: 'Target arch of the kernel, required for finding the image'
    required: true
  archive:
    description: 'Path to the output archive'
    required: true
  kbuild-output:
    description: 'Path to the kernel build output for archiving'
    required: true
  repo-root:
    description: "Path to the root of the kernel repository"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run tar-artifacts.sh
      env:
        KBUILD_OUTPUT: ${{ inputs.kbuild-output }}
        REPO_ROOT: ${{ inputs.repo-root }}
        ARCH: ${{ inputs.arch }}
      shell: bash
      run:
        ${GITHUB_ACTION_PATH}/tar-artifacts.sh ${{ inputs.archive }}
