name: 'build linux'
description: 'Build Linux'
inputs:
  arch:
    description: 'arch'
    required: true
  toolchain:
    description: 'what toolchain to use'
    default: 'gcc'
  kbuild-output:
    description: 'relative or absolute path to use for storing build artifacts'
    required: true
  max-make-jobs:
    description: 'Maximum number of jobs to use when running make (e.g argument to -j). Default: 4*nproc'
    default: ''
  llvm-version:
    description: 'llvm version'
    required: false
    default: '16'
runs:
  using: 'docker'
  image: ghcr.io/theihor/kbuilder-test
  args:
    - ${{ inputs.arch }}
    - ${{ inputs.toolchain }}
    - ${{ inputs.kbuild-output }}
  env:
    MAX_MAKE_JOBS: ${{ inputs.max-make-jobs }}
