---

- name: Create runner directory
  become: yes
  ansible.builtin.file:
    path: "{{ runner_base_dir }}"
    state: directory
    mode: 0755

- include_tasks: main-s390x.yml
  when: ansible_architecture == 's390x'

- include_tasks: main-generic.yml
  when: ansible_architecture != 's390x'

- name: Set docker pruning service
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/system/docker_pruning.service
    content: |
      [Unit]
      Description=Prune unused docker resources
      Wants=docker_pruning.timer

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/docker system prune --volumes -f
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd daemon
    - restart docker_pruning timer


- name: Set docker pruning timer
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/system/docker_pruning.timer
    content: |
      [Unit]
      Description=Run docker_pruning service daily

      [Timer]
      # Run at 8:00 UTC daily
      OnCalendar=*-*-* 08:00:00
      [Install]
      WantedBy=timers.target
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd daemon
    - restart docker_pruning timer

- name: Enable docker pruning timer
  become: yes
  ansible.builtin.service:
    name: docker_pruning.timer
    enabled: yes
    state: started
