---

- name: Get account $HOME
  shell: "echo $HOME"
  register: account_homedir
  changed_when: false
  check_mode: no

- name: Sync libbpf/ci repo
  ansible.builtin.git:
    repo: "{{ runner_libbpf_ci_repo_url }}"
    update: yes
    dest: "{{ account_homedir.stdout }}/libbpf-ci"
    version: "{{ runner_libbpf_ci_repo_branch }}"
    accept_hostkey: yes

- name: Set docker image URL
  set_fact:
    runner_docker_image_url: kernel-patches/runner

- name: Build runner docker image
  become: yes
  shell:
    "docker build --pull -f actions-runner-libbpf.Dockerfile -t {{ runner_docker_image_url }}:{{ runner_docker_tag }} ."
  args:
    chdir: "{{ account_homedir.stdout }}/libbpf-ci/rootfs/s390x-self-hosted-builder"