---

# Used by ansible modules later
- name: Install docker/boto3 pip
  become: yes
  ansible.builtin.pip:
    name:
      - docker
      - boto3
    extra_args: --user

- name: Set runner env
  become: yes
  ansible.builtin.copy:
    dest: "{{ runner_base_dir }}/runner_unit.env"
    content: |
      DOCKER_TAG={{ runner_docker_tag }}
    mode: 0700
    owner: root
    group: root

- name: Generate runner environment file
  block:
    - name: Load ec2 metadata facts
      amazon.aws.ec2_metadata_facts:

    - name: Retrieve all tags on an instance
      become: yes
      amazon.aws.ec2_tag_info:
        region: "{{ ansible_ec2_placement_region }}"
        resource: "{{ ansible_ec2_instance_id }}"
      register: instance_tags

    - name: Generate runner env file
      become: yes
      ansible.builtin.copy:
        dest: "{{ runner_base_dir }}/{{ 'runner_%02d.env' | format(item) }}"
        content: |
          ACCESS_TOKEN={{ runner_gh_token_default }}
          RUNNER_WORKDIR=/tmp/work
          LABELS=ubuntu-latest,docker-{{ runner_docker_tag }}
          EPHEMERAL=true
          REPO_URL={{ instance_tags.tags['Repo'] }}
          RUNNER_NAME={{ ansible_ec2_instance_id }}-{{ 'worker-%02d' | format(item) }}
      loop: "{{ range(0, runner_workers, 1)|list }}"
  rescue:
    - name: Generate runner env outside AWS
      become: yes
      ansible.builtin.copy:
        dest: "{{ runner_base_dir }}/{{ 'runner_%02d.env' | format(item) }}"
        content: |
          ACCESS_TOKEN={{ runner_gh_token_default }}
          RUNNER_WORKDIR=/tmp/work
          LABELS=ubuntu-latest,docker-{{ runner_docker_tag }}
          EPHEMERAL=true
          REPO_URL=https://github.com/{{ runner_repo_list[0].name }}
          RUNNER_NAME={{ inventory_hostname }}-{{ 'worker-%02d' | format(item) }}
      loop: "{{ range(0, runner_workers, 1)|list }}"

- name: Docker GHCR login
  become: yes
  docker_login:
    registry: ghcr.io
    username: "{{ runner_gh_user_default }}"
    password: "{{ runner_gh_token_default }}"

- name: Check /dev/kvm exists
  ansible.builtin.stat:
    path: /dev/kvm
  register: has_kvm

- name: Set runner.service
  become: yes
  ansible.builtin.copy:
    dest: "/etc/systemd/system/runner@.service"
    content: |
      [Unit]
      Description=Ephemeral GitHub Actions Runner Container %i
      After=docker.service
      Requires=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      EnvironmentFile={{ runner_base_dir }}/runner_unit.env
      ExecStartPre=-/usr/bin/docker stop %P-%i
      ExecStartPre=-/usr/bin/docker rm %P-%i
      ExecStartPre=-/usr/bin/docker pull ghcr.io/kernel-patches/runner:${DOCKER_TAG}
      ExecStartPre=-/usr/bin/docker system prune -f
      ExecStart=/usr/bin/docker run {{ '--device=/dev/kvm' if has_kvm.stat.exists }} --rm --env-file "{{ runner_base_dir }}/runner_%i.env" --name %P-%i ghcr.io/kernel-patches/runner:${DOCKER_TAG}
    mode: 0700
    owner: root
    group: root
  notify:
    - reload systemd daemon

- name: Start and enable runner services
  become: yes
  ansible.builtin.service:
    name: "{{ 'runner@%02d' | format(item) }}"
    state: started
    enabled: yes
  loop: "{{ range(0, runner_workers, 1)|list }}"