name: 'build selftests'
description: 'Build BPF selftests'
inputs:
  arch:
    description: 'arch'
    required: true
  kernel-root:
    description: 'Path to the root of the kernel source tree'
    required: true
  llvm-version:
    description: 'llvm version'
    required: false
    default: '18'
  toolchain:
    description: 'gcc or llvm'
    default: 'gcc'

runs:
  using: "composite"
  steps:
    - name: build selftests
      shell: bash
      env:
        ARCH: ${{ inputs.arch }}
        KERNEL_ROOT: ${{ inputs.kernel-root }}
        LLVM_VERSION: ${{ inputs.llvm-version }}
        TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        ${GITHUB_ACTION_PATH}/build_selftests.sh "${ARCH}" "${TOOLCHAIN}" "${KERNEL_ROOT}"

