name: 'build selftests'
description: 'Build BPF selftests'
inputs:
  kernel:
    description: 'kernel version'
    default: 'LATEST'
  toolchain:
    description: 'what toolchain to use'
    default: 'gcc'
  kbuild-output:
    description: 'relative or absolute path to use for storing build artifacts'
    default: '.'
runs:
  using: "composite"
  steps:
    - name: build selftests
      shell: bash
      run: |
        kbuild_output="$(realpath ${{ inputs.kbuild-output }})"
        ${GITHUB_ACTION_PATH}/build_selftests.sh "${{ inputs.kernel }}" "${{ inputs.toolchain }}" "${kbuild_output}"
