name: 'build selftests'
description: 'Build BPF selftests'
inputs:
  vmlinux_btf:
    description: 'path to vmlinux BTF file'
    required: true
  kernel:
    description: 'kernel version'
    default: 'LATEST'
  toolchain:
    description: 'what toolchain to use'
    default: 'gcc'
runs:
  using: "composite"
  steps:
    - name: build selftests
      shell: bash
      run: ${GITHUB_ACTION_PATH}/build_selftests.sh "${{ inputs.vmlinux_btf }}" "${{ inputs.kernel }}" "${{ inputs.toolchain }}"
