name: 'prepare-rootfs'
description: 'build rootfs
1. download base root img to /tmp/root.img (or other path, if provided)
2. either copy "/vmlinux" or download "vmlinux" to "/boot" in image
3. (FIXME) either copy "/vmlinuz" from build dir or download "vmlinuz" to workspace root
4. copy hardcoded "selftests" and "ci/vmtest" directory to "/$PROJECT_NAME" in root image
'
inputs:
  project-name:
    description: 'project name'
    required: true
  arch:
    description: 'arch'
    required: true
  kernel:
    description: 'kernel version; use LATEST to use the most recent version'
    required: true
  kernel-root:
    description: 'kernel source dir'
    required: true
  kbuild-output:
    description: 'relative or absolute path to use for storing build artifacts'
    default: ''
  image-output:
    description: 'path where to store the generated image'
    required: true
  test:
    description: 'the name of the test to run'
    default: ''
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        export REPO_ROOT="${{ github.workspace }}"
        export KERNEL="${{ inputs.kernel }}"
        export KERNEL_ROOT="${{ inputs.kernel-root }}"
        kbuild_output="$(realpath ${{ inputs.kbuild-output }})"
        $GITHUB_ACTION_PATH/run_vmtest.sh "${kbuild_output}" ${{ inputs.image-output }} ${{ inputs.test }}
      shell: bash
      env:
        PROJECT_NAME: ${{ inputs.project-name }}
        TARGET_ARCH: ${{ inputs.arch }}
