name: 'Prepare incremental kernel build'
description: 'Pull cached kernel build output from previous runs and prepare the repo for incremental build'
inputs:
  repo-root:
    description: "Root of the kernel repository"
    required: true
    default: ${{ github.workspace }}
  base-branch:
    description: "Base branch for cache lookup"
    required: true
    default: bpf-next_base
  arch:
    required: true
    type: string
    description: "Part of cache lookup key"
  toolchain_full:
    required: true
    type: string
    description: "Part of cache lookup key"
  kbuild-output:
    required: true
    type: string
    description: "Path to KBUILD_OUTPUT"
    default: kbuild-output

runs:
  using: "composite"
  steps:

    - name: Get commit meta-data for cache lookup
      id: get-commit-metadata
      shell: bash
      working-directory: ${{ inputs.repo-root }}
      run: ${GITHUB_ACTION_PATH}/get-commit-metadata.sh ${{ inputs.base-branch }}

    - name: Pull recent KBUILD_OUTPUT contents
      uses: actions/cache@v4
      with:
        path: ${{ inputs.kbuild-output }}
        key: kbuild-output-${{ inputs.arch }}-${{ inputs.toolchain_full }}-${{ steps.get-commit-metadata.outputs.branch }}-${{ steps.get-commit-metadata.outputs.timestamp }}-${{ steps.get-commit-metadata.outputs.commit }}
        restore-keys: |
          kbuild-output-${{ inputs.arch }}-${{ inputs.toolchain_full }}-${{ steps.get-commit-metadata.outputs.branch }}-${{ steps.get-commit-metadata.outputs.timestamp }}-
          kbuild-output-${{ inputs.arch }}-${{ inputs.toolchain_full }}-${{ steps.get-commit-metadata.outputs.branch }}-
          kbuild-output-${{ inputs.arch }}-${{ inputs.toolchain_full }}-

    - name: Prepare incremental build
      shell: bash
      env:
        KBUILD_OUTPUT: ${{ inputs.kbuild-output }}
      working-directory: ${{ inputs.repo-root }}
      run: ${GITHUB_ACTION_PATH}/prepare-incremental-builds.sh ${{ steps.get-commit-metadata.outputs.commit }}

