name: 'setup build env'
description: 'Setup build env'
inputs:
  pahole:
    description: 'pahole rev/tag/branch'
    required: true
    default: 'master'
  pahole-origin:
    description: 'pahole repo'
    required: true
    default: 'https://git.kernel.org/pub/scm/devel/pahole/pahole.git'
  llvm-version:
    description: 'llvm version'
    required: false
    default: '16'
  gcc-version:
    required: false
    default: '13'
  arch:
    description: 'arch'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup environment
      shell: bash
      env:
        GCC_VERSION: ${{ inputs.gcc-version }}
        LLVM_VERSION: ${{ inputs.llvm-version }}
        PAHOLE_BRANCH: ${{ inputs.pahole }}
        PAHOLE_ORIGIN: ${{ inputs.pahole-origin }}
        TARGET_ARCH: ${{ inputs.arch }}
      run: |
        ${GITHUB_ACTION_PATH}/action.sh
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:/usr/local/lib" >> $GITHUB_ENV
