name: 'setup build env'
description: 'Setup build env'
inputs:
  pahole:
    description: 'pahole rev/tag/branch'
    required: true
    default: 'master'
  pahole-origin:
    description: 'pahole repo'
    required: true
    default: 'https://git.kernel.org/pub/scm/devel/pahole/pahole.git'
  llvm-version:
    description: 'llvm version'
    required: false
    default: '16'
  gcc-version:
    required: false
    default: '13'
  arch:
    description: 'arch'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup environment
      shell: bash
      env:
        GCC_VERSION: ${{ inputs.gcc-version }}
      run: |
        ${GITHUB_ACTION_PATH}/install_packages.sh
    - name: Install clang
      shell: bash
      env:
        LLVM_VERSION: ${{ inputs.llvm-version }}
      run: |
        ${GITHUB_ACTION_PATH}/install_clang.sh
    - name: Install pahole
      shell: bash
      env:
        PAHOLE_BRANCH: ${{ inputs.pahole }}
        PAHOLE_ORIGIN: ${{ inputs.pahole-origin }}
      run: |
        ${GITHUB_ACTION_PATH}/build_pahole.sh
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:/usr/local/lib" >> $GITHUB_ENV
    - name: Install cross compilation toolchain
      shell: bash
      env:
        GCC_VERSION: ${{ inputs.gcc-version }}
      run: |
         ${GITHUB_ACTION_PATH}/install_cross_compilation_toolchain.sh ${{ inputs.arch }}
