name: 'patch kernel tree'
description: 'patch kernel'
inputs:
  patches-root:
    description: "Directory to find patches"
    required: true
    default: ./ci/diffs
  repo-root:
    description: "Directory to apply patch to"
    required: true
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:
    - name: apply temporary patches
      shell: bash
      env:
        REPO_ROOT: ${{ inputs.repo-root }}
        PATCHES_ROOT: ${{ inputs.patches-root }}
      run: cd ${REPO_ROOT} && ${GITHUB_ACTION_PATH}/patch_kernel.sh "${PATCHES_ROOT}"
