name: 'patch kernel tree'
description: 'patch kernel'
inputs:
  patches-root:
    description: "Directory to find patches"
    required: true
    default: ./ci/diffs
  repo-root:
    description: "Directory to apply patch to"
    required: true
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:
    - name: apply temporary patches
      shell: bash
      run: cd ${{ inputs.repo-root }} && ${GITHUB_ACTION_PATH}/patch_kernel.sh "${{ inputs.patches-root }}"
