name: 'download-vmlinux'
description: 'Download prebuilt vmlinux image'
inputs:
  kernel:
    description: 'kernel version'
    required: true
  arch:
    description: 'arch'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download prebuilt vmlinux
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        ARCH: ${{ inputs.arch }}
        KERNEL: ${{ inputs.kernel }}
      run: |
        ${ACTION_PATH}/run.sh -k "${KERNEL}"
