name: 'get-llvm-version'
description: 'Retrieve the LLVM version to use'
outputs:
  version:
    description: "LLVM version"
    value: ${{ steps.llvm-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: llvm-version
      shell: bash
      run: echo "version=$(source $GITHUB_ACTION_PATH/../helpers.sh; llvm_default_version)" >> $GITHUB_OUTPUT
