name: 'run qemu'
description: 'Run qemu with given rootfs and print summary'
inputs:
  arch:
    description: 'arch'
    required: true
  img:
    description: 'img path'
    required: true
  vmlinuz:
    description: 'vmlinuz path'
    required: true
  kernel-root:
    description: 'kernel source dir'
    default: '.'
runs:
  using: "composite"
  steps:
    - name: test
      shell: bash
      env:
        VMLINUZ: ${{ inputs.vmlinuz }}
        IMG: ${{ inputs.img }}
        KERNEL_ROOT: ${{ inputs.kernel-root }}
      run: |
        ARCH="${{ inputs.arch }}" ${GITHUB_ACTION_PATH}/run.sh
