name: "Test actions"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test_run_vmtest:
    name: Test run-vmtest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test print_test_summary
        run: ./run-vmtest/print_test_summary.py  -j run-vmtest/fixtures/test_progs.json -s "${GITHUB_STEP_SUMMARY}"
