name: "Test actions"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test_run_qemu:
    name: Test run-qemu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test print_test_summary
        working-directory: run-qemu
        run: python3 -m unittest tests/test_run_qemu.py
