name: "Test actions"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test_run_vmtest:
    name: Test run-vmtest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Execute run-vmtest/tests
        run: ./run-vmtest/tests/run-all-tests.sh
